### ISSUE TITLE
Dependency Pate does not build on Debian/Ubuntu and is unmaintained.

### ISSUE THREAD

**Issue by justinzane** [goinnn/Kate-plugins#13]
https://github.com/pag/pate/issues/2

I cannot build Pate on Kubuntu 12.10, and as the above issue indicates, this is a known problem for Debian based distros. It also appears that @pag is no longer using or maintaining Pate.

**Comment by goinnn** [comment]
@justinzane you are wrong. Pate is not unmaintained. Pate now belongs to the official source of Kate

https://projects.kde.org/projects/kde/kde-baseapps/kate/repository/show/kate/plugins/pate
