### ISSUE TITLE
Autocomplete plugins crash in KDE 4.8.2

### ISSUE THREAD

**Issue by ablanco** [goinnn/Kate-plugins#9]
Both plugins (JavaScript and Python) crash while loading, both with the same error:

```
Traceback (most recent call last):
File "/home/korosu/.kde4/share/apps/kate/pate/kate_plugins/kate_plugins.py", line 1, in <module>
    from jste_plugins.autocomplete import *
File "/home/korosu/.kde4/share/apps/kate/pate/kate_plugins/jste_plugins/autocomplete.py", line 6, in <module>
    from autopate import AbstractJSONFileCodeCompletionModel
File "/home/korosu/.kde4/share/apps/kate/pate/kate_plugins/autopate.py", line 9, in <module>
    class AbstractCodeCompletionModel(KTextEditor.CodeCompletionModel):
File "/home/korosu/.kde4/share/apps/kate/pate/kate_plugins/autopate.py", line 26, in AbstractCodeCompletionModel
    KTextEditor.CodeCompletionModel.Prefix),
TypeError: PyQt4.QtCore.QVariant represents a mapped type and cannot be instantiated
Could not load plugin kate_plugins
```

And when the JavaScript autocomplete plugin is commented:

```
Traceback (most recent call last):
File "/home/korosu/.kde4/share/apps/kate/pate/kate_plugins/kate_plugins.py", line 9, in <module>
    from pyte_plugins.autocomplete.autocomplete import *
File "/home/korosu/.kde4/share/apps/kate/pate/kate_plugins/pyte_plugins/autocomplete/autocomplete.py", line 8, in <module>
    from autopate import AbstractCodeCompletionModel
File "/home/korosu/.kde4/share/apps/kate/pate/kate_plugins/autopate.py", line 9, in <module>
    class AbstractCodeCompletionModel(KTextEditor.CodeCompletionModel):
File "/home/korosu/.kde4/share/apps/kate/pate/kate_plugins/autopate.py", line 26, in AbstractCodeCompletionModel
    KTextEditor.CodeCompletionModel.Prefix),
TypeError: PyQt4.QtCore.QVariant represents a mapped type and cannot be instantiated
Could not load plugin kate_plugins
```

**Comment by goinnn** [comment]
It is possible that the QVariant implementation has changed. These errors are very complicated to fix.

I would accept a pull request :-). But if you can not devote some hours, someday we can try fix the problem together.

**Comment by ablanco** [comment]
If you import sip, and ask for version, what is the output? Mine:

```
sip.SIP_VERSION_STR
'4.13.2'
```

**Comment by goinnn** [comment]
This is my sip version: 4.9.1-snapshot-20091015

**Comment by ablanco** [comment]
I've tried it in another laptop with the same OS and same sip version (4.13.2) and it works! I think we can rule sip out, it must be something else.

**Comment by goinnn** [comment]
I had problems when I update the version of OS, and I had to freeze some packages: python-qt-dev, python-qt4, python-sip, python-sip4, python-sip4-dev, python-sip-dev, python-sip4-dev and sip4

Perhaps the solution is there

**Comment by javiromero** [comment]
Maybe I can also help narow the problem, I'm on archlinux, everything up to date: KDE 4.8.4, Kate 3.8.4, SIP 4.13.2

I also have both Python 2.7 and Python 3.2.3 installed, may that have something to do?
What's the next I should look for?

**Comment by goinnn** [comment]
Thanks you!
- Install the project [1]
- Run kate (from console to see the errors)
- Enable the Pâté plugin in Kate settings
- Write something like this: "from o"
- Press Ctrl + space bar
- If autocomplete no problem. Else some problem, close the kate and test a second time, it's possible that the first time this does not work

REF:
1. https://github.com/goinnn/Kate-plugins#installation

**Comment by javiromero** [comment]
Thank you for the instructions.

Regarding the install process, should I use Python 3's or 2's easy_install? As I have both installed on the system and currently I've installed Kate-plugins using easy_install-2.7. Or is it irrelevant?

For reference, I also have installed:
python 3.2.3
python2 2.7.3
kdebindings-python 4.8.4
kdebindings-python2 4.8.4
pate-git 20120612
pep8 1.2
pyqt 4.9.1
sip 4.13.2
python2-pyqt 4.9.1
python2-sip 4.13.2

**Comment by goinnn** [comment]
I use python 2.7. @ablanco said that he has python 2.7 and python 3.2, but he did not say which one used. I would try with python 2.7

**Comment by ablanco** [comment]
I used python 2.7 too.

**Comment by goinnn** [comment]
@javiromero any problem?

**Comment by javiromero** [comment]
I'm afraid I've reached the same status that ablanco

The Python Console item is shown under the View menu but there's no autocomplete or other functions working

> Traceback (most recent call last):
>  File "/home/javi/.kde4/share/apps/kate/pate/kate_plugins/kate_plugins.py", line 1, in <module>
>    from jste_plugins.autocomplete import *
>  File "/home/javi/.kde4/share/apps/kate/pate/kate_plugins/jste_plugins/autocomplete.py", line 6, in <module>
>    from autopate import AbstractJSONFileCodeCompletionModel
>  File "/home/javi/.kde4/share/apps/kate/pate/kate_plugins/autopate.py", line 9, in <module>
>    class AbstractCodeCompletionModel(KTextEditor.CodeCompletionModel):
>  File "/home/javi/.kde4/share/apps/kate/pate/kate_plugins/autopate.py", line 26, in AbstractCodeCompletionModel
>    KTextEditor.CodeCompletionModel.Prefix),
> TypeError: PyQt4.QtCore.QVariant represents a mapped type and cannot be instantiated
> Could not load plugin kate_plugins

**Comment by ghost** [comment]
Removing QVariant should work. I'm currently trying to get it working in a fork of Kate-plugins. Will send a pull-request if i'm able to fix it.

**Comment by goinnn** [comment]
@phrearch I saw it. Thank you very much! I am sure that you will get it. My problem is that works in my machine. Certainly you have a little error, you did not refactor the TITLE_AUTOCOMPLETATION in the kate_plugins/jste_plugins/autocomplete.py and kate_plugins/pyte_plugins/autocomplete/autocomplete.py files. Thanks to fix my english, this is horrible :-)

If you need something tell me

**Comment by goinnn** [comment]
The [pull request](https://github.com/goinnn/Kate-plugins/pull/10) fix the problem. Thanks to all: @ablanco, 
@javiromero, @phrearch
